Added single unit tests
Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -111,14 +111,88 @@ jobs:
           sudo microceph.ceph -s
           ~/actionutils.sh wait_for_osds 3
           sudo microceph.ceph -s
-          
-  juju-test:
+
+  juju-cluster-test:
     needs:
       - lint
       - unit-test
       - build
     name: Juju test
-    runs-on: [self-hosted, xxlarge]
+    runs-on: [self-hosted, xlarge]
+    steps:
+
+      - name: Download charm
+        uses: actions/download-artifact@v3
+        with:
+          name: charms
+          path: ~/artifacts/
+
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Setup LXD
+        uses: canonical/setup-lxd@v0.1.1
+
+      - name: Install dependencies
+        run: |
+          date
+          sudo snap install juju
+          mkdir -p ~/.local/share/juju
+          juju bootstrap localhost
+          juju add-model microceph-test
+          date
+
+      - name: Install MicroCeph charm
+        run: |
+          date
+          juju deploy -n 3 ~/artifacts/microceph.charm
+          juju wait-for application microceph --query='name=="microceph" && (status=="active" || status=="idle")'
+          date
+
+      - name: Show Juju status
+        run: |
+          set -eux
+          juju status
+
+      - name: Add disks
+        run: |
+          set -eux
+          juju run microceph/0 add-osd loop-spec=4G,1 --wait=2m
+          juju run microceph/1 add-osd loop-spec=4G,1 --wait=2m
+          juju run microceph/2 add-osd loop-spec=4G,1 --wait=2m
+
+      - name: Remove Unit
+        run: |
+          set -x
+          juju remove-unit microceph/2 --no-prompt
+          # wait and check if the unit is still present.
+          for i in $(seq 1 8); do
+            res=$( ( juju status | grep -cF "microceph/2" ) || true )
+            if [[ $res -gt 0 ]] ; then
+              echo -n '.'
+              sleep 5
+            else
+              echo "Unit removed successfully"
+              break
+            fi
+          done
+          # fail if unit still present.
+          if [[ $res -gt 0 ]] ; then
+            echo "Unit still present"
+            juju status
+            exit 1
+          fi
+          juju exec --unit microceph/0 -- microceph status
+
+  juju-single-test:
+    needs:
+      - lint
+      - unit-test
+      - build
+    name: Juju test
+    runs-on: [self-hosted, xlarge]
     steps:
 
       - name: Download charm
@@ -148,20 +222,17 @@ jobs:
         run: |
           date
           # constraints to deploy on virtual machine.
-          juju deploy -n 3 ~/artifacts/microceph.charm --storage osd-devices='4G,1' --constraints="virt-type=virtual-machine root-disk=40G mem=8G"
+          juju deploy ~/artifacts/microceph.charm --storage osd-devices='4G,3' --constraints="virt-type=virtual-machine root-disk=40G mem=8G"
           juju wait-for application microceph --query='name=="microceph" && (status=="active" || status=="idle")'
+          juju status
           date
 
-      - name: Show Juju status
-        run: |
-          set -eux
-          juju status
-
-      - name: Remove Juju Storage device
+      - name: Remove Juju Storage
         run: |
           set -eux
           juju detach-storage osd-devices/0
           juju wait-for application microceph --query='name=="microceph" && (status=="blocked")'
+          juju status
           date
 
       - name: Add OSDs with WAL/DB
@@ -217,3 +288,5 @@ jobs:
             exit 1
           fi
           juju exec --unit microceph/0 -- microceph status
+          juju status
+          date
